---
title: "top500"
output: html_document
date: "2023-04-12"
---

This script takes the top 500 list and runs it through gbif via taxize and worms via worrms

to do: update column headers to be useful, coalesce into found-species column


```{r setup, include=FALSE}
library(tidyverse)
library(worrms)
library(taxize)
library(here)


# here filepaths
splists <- here('processeddata', 'species_lists', 'region')
```

This function pulls from worms using worrms
```{r worms-function}
## requires worrms to be loaded
# input is vector of species names
# use wm_records_names to extract 
# this doesn't need the + signs

# right now this breaks if not-found
search_records_worms <- function(spnames) {
  search <- tibble()
  for (i in spnames) {
    print(paste0('searching for ', i))
    record <- wm_records_names(i, marine_only = FALSE)
    message('done')
    search <- append(search, record)
  }
  names(search) <- spnames
  search_output <- map_dfr(.x = search, ~ data.frame(.x), .id = 'query') %>%
    janitor::clean_names() %>%
    select(!(c(url, taxon_rank_id, citation, lsid, modified)))
  return(search_output)
}
```


```{r load-in}
top500_mifish <- read.delim(here("rawdata", "top500_20230405",
                                   "blast_96_sim_LCA_besthit", "12S_ASV_sequences.length_var.blast.out"), 
                           h = TRUE, fill = TRUE) %>% 
  # standardize names and remove overhanging x
  janitor::clean_names() %>%
  rename_with(., ~str_remove_all(string = .,
                 pattern = "x_")) %>%
  separate_wider_delim(taxonomy, delim = ' / ', 
                       names = c('kingdom', 'phylum', 'class', 'order', 
                                 'family', 'genus', 'species')) %>%
  # column to match existing scripts
  rename(asv = query_id) %>%
  filter(kingdom == "Eukaryota")
```



```{r}
top500_sp <- top500_mifish %>%
  filter(class %in% c("Actinopteri", "Chondrichthyes"))  %>% 
  select(c("species")) %>%
  distinct() 

# use gbif to resolve the initial round of NCBI dirty names
top500_ids <- get_gbifid_(top500_sp$species)

# results to dataframe
top500_ids2 <- map_dfr(.x= top500_ids, ~ data.frame(.x), .id = 'taxa_query') %>%
  filter(kingdom == "Animalia") %>%
  # eliminating fuzzy matches for now
  filter(matchtype == 'EXACT') %>%
  # strip higher taxonomy from gbif bc it doesn't match worms/bold
  ## but keep keys!
  select(taxa_query, canonicalname, rank, status)
 
# update species list with gbif results  
top500_sp   <- top500_sp %>%
  left_join(top500_ids2, by = c('species' = 'taxa_query')) %>%
  rename(ncbi_species = species) %>%
  mutate(species = coalesce(canonicalname, ncbi_species)) %>%
  distinct() %>%
  group_by(species) %>%
  add_count() %>%
  ungroup() %>%
  mutate(remove_me = ifelse((ncbi_species == canonicalname & n > 1 & status != 'ACCEPTED'), 1, 0)) %>%
  filter(remove_me == 0) %>%
  select(!(c('remove_me', 'n'))) %>%
  mutate(worms_query = gsub(" ", "+", species)) %>%
  rename(query = species,
         gbif_status = status) 

# generate search for worms, given curl error
top500_search <- top500_sp %>%
  select(query, worms_query) %>%
  distinct()
  
  

# worms id
# we only want to search for species that are in worms, or we'll get errors
top500_worms <- get_wormsid_(sci_com = top500_search$worms_query, marine_only = FALSE,
                           accepted = FALSE)
# get_wormsid_ gives back null and length 0 elements
## first remove with compact and discard then map_dfr
top500_worms2 <- top500_worms %>% 
  compact() %>%
  discard( ~ nrow(.x) == 0) %>%
  map_dfr( ~ data.frame(.x), .id = 'worms_query') %>%
  rename(worms_status = status) %>%
  # remove unnecessary subspecies
  ## either TWO plus signs in query (subspecies query, keep subspecies result) OR
  ## ONE space in results (species query = species result)
  filter((str_detect(worms_query, regex("(\\+)[a-z]*(\\+)"))) |
           str_detect(scientificname, regex("^[A-Z,a-z]+(\\s)[a-z]*$"))
           ) %>%
  rename(worms_sciname = scientificname,
         worms_aphiaid = AphiaID) %>%
  select(!(authority)) %>%
  distinct()
  

## Add the count removal later

top500_records <- search_records_worms(unique(top500_worms2$worms_sciname))


# refine results to be useful
top500_records2 <- top500_records %>%
  # only animal hits
  filter(kingdom == 'Animalia') %>%
  # generate terrestrial-only and freshwater-only columns
  mutate(freshwater_only = ifelse((is_marine %in% c(0, NA) ==TRUE) & (is_brackish %in% c(0,NA) == TRUE) & (is_freshwater == 1),  "1", "0")) %>%
    mutate(terrestrial_only = ifelse((is_marine %in% c(0, NA) ==TRUE) & (is_brackish %in% c(0,NA) == TRUE) & (is_terrestrial == 1),  "1", "0")) %>%
  distinct() %>%
  # rename to format
  rename(worms_aphiaid = valid_aphia_id,
         original_aphiaid =aphia_id,
         worms_match = scientificname,
         worms_sciname = valid_name
         ) %>%
  # remove unneeded columns
  select(!(c(authority, parent_name_usage_id, is_freshwater, 
             is_terrestrial, is_marine, is_brackish, is_extinct, match_type))) %>%
  relocate(c(worms_sciname, worms_aphiaid), .before = original_aphiaid) %>%
  # rank lowercase
  mutate(rank = tolower(rank))









# update species list with worms results
top500_sp <- top500_sp %>%
  left_join(top500_records2) 






```



```{r}
write_csv(top500_sp, here('rawdata', 'top500_20230405', '20230413_top500-worrms.csv'))
```

